export const GETING_ARTICLES = 'GETING_ARTICLES';
export const POSTING_ARTICLE = 'POSTING_ARTICLE';
export const PUTING_ARTICLE = 'PUTING_ARTICLE';
export const GETING_ARTICLES_CATEGORY = 'GETING_ARTICLES_CATEGORY';
export const GETING_ARTICLES_TITLE = 'GETING_ARTICLES_TITLE';
export const DELETING_ARTICLE = 'DELETING_ARTICLE';
export const POSTING_CATEGORY = 'POSTING_CATEGORY';
export const DELETING_CATEGORY = 'DELETING_CATEGORY';
export const GETING_ONE_ARTICLE = 'GETING_ONE_ARTICLE';

export const GET_ARTICLES = 'GET_ARTICLES';
export const POST_ARTICLE = 'POST_ARTICLE';
export const PUT_ARTICLE = 'PUT_ARTICLE';
export const GET_ARTICLES_CATEGORY = 'GET_ARTICLES_CATEGORY';
export const GET_ARTICLES_TITLE = 'GET_ARTICLES_TITLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const POST_CATEGORY = 'POST_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_ONE_ARTICLE = 'GET_ONE_ARTICLE';

export const MOVING_TO_TRASH = 'MOVE_TO_TRASH';

export const MOVE_TO_TRASH = 'MOVE_TO_TRASH';

export const BE_TRUE = 'BE_TRUE';
export const BE_FALSE = 'BE_FALSE';

